exclude_local:
  - trash:///
  - ~/.local/share/Trash
  - ~/.arduino15
  - ~/.arduino
  - ~/Desktop
  - ~/Downloads
  - ~/Dropbox (ASU)/code_external
  - ~/Arizona State University
  - ~/cloud
  - ~/nas
  - ~/code_external
exclude_remote:
  - Comprehensive_Presentation.git
  - Comprehensive_Exam_Mohammad_Sharifzadeh.git
  - hmil
  - asu-unity-stack  
index_depth: 5
index_location: '~'
clone_path: '~/repositories'
archive_path: '~/repositories/dormant'
index_cache: '~/repositories.yaml'